export default function About() {
  const principles = [
    { icon: "🔒", title: "Privacy by design", desc: "We aim to collect only the information needed to provide the service and protect it with access controls." },
    { icon: "🧭", title: "Reflection, not dependence", desc: "Readings are prompts for self-reflection. You remain responsible for your decisions." },
    { icon: "📋", title: "Clear product scope", desc: "We describe and sell only features that are currently available on the site." },
    { icon: "⚖️", title: "Entertainment and wellness", desc: "MysticSage does not provide medical, legal, financial, or crisis advice." },
  ];
  return <><section className="page-header"><h1>About MysticSage</h1><p>AI-powered tarot for reflection and spiritual wellness.</p></section><section className="section"><div className="container" style={{ maxWidth: 840, margin: "0 auto" }}><div className="section-tag">Our approach</div><h2 className="section-title">Ancient symbolism, modern reflection</h2><p style={{ color: "var(--text-secondary)", marginTop: 16, lineHeight: 1.8 }}>MysticSage is a digital tool for people who want to pause, explore a question, and reflect on tarot symbolism. The product currently offers free three-card readings, one-time detailed tarot reports, and Mystic Plus premium readings.</p><p style={{ color: "var(--text-muted)", marginTop: 16, lineHeight: 1.8 }}>The site does not claim to predict a fixed future. Readings are for entertainment and spiritual wellness only, and they are not a substitute for professional help or advice.</p></div></section><section className="section"><div className="container"><div className="section-tag">Principles</div><h2 className="section-title">What guides the product</h2><div className="services-grid">{principles.map(principle => <div className="service-card" key={principle.title}><span className="icon">{principle.icon}</span><h3>{principle.title}</h3><p>{principle.desc}</p></div>)}</div></div></section></>;
}
