import Link from "next/link";
import { blogPosts } from "@/content/blog";

export default function Home() {
  const latestPosts = [...blogPosts].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()).slice(0, 3);
  return <><section className="hero"><div className="container hero-grid"><div><div className="section-tag">Tarot for Reflection</div><h1>Your next moment of <span className="highlight">clarity</span> starts here</h1><p>MysticSage offers AI-powered tarot readings for reflection and spiritual wellness. Use the cards as a prompt to explore your own perspective, not as a prediction or professional advice.</p><div className="hero-buttons"><Link href="/reading" className="btn-primary">✦ Try a Free Tarot Reading</Link><Link href="/pricing" className="btn-secondary">View Pricing</Link></div></div><div className="hero-visual"><div className="hero-card"><div className="card-badge">Free three-card reading</div><div className="card-title">A moment to reflect</div><div className="card-cards"><div className="mini-card" style={{ background: "linear-gradient(145deg,rgba(180,100,255,0.15),rgba(88,56,250,0.08))" }}>🌙</div><div className="mini-card" style={{ background: "linear-gradient(145deg,rgba(80,150,255,0.15),rgba(80,200,120,0.08))" }}>⭐</div><div className="mini-card" style={{ background: "linear-gradient(145deg,rgba(255,200,50,0.15),rgba(180,100,255,0.08))" }}>🔮</div></div><div style={{ fontSize: 13, color: "var(--text-muted)", lineHeight: 1.5 }}>Ask an open-ended question, draw three cards, and use the interpretation as a starting point for reflection.</div><Link href="/reading" className="card-cta" style={{ display: "block" }}>Pull Your Cards</Link></div></div></div></section>
    <section className="section" id="services"><div className="container"><div className="section-tag">Available today</div><h2 className="section-title">Two clear ways to go deeper</h2><p className="section-sub">The public product catalog contains only the experiences that are currently delivered by the site.</p><div className="services-grid">{[{ icon: "🔮", title: "Free Tarot", desc: "One daily three-card AI tarot reading, with no payment required." }, { icon: "📜", title: "Detailed Report", desc: "A one-time 10-card Celtic Cross report, generated after payment verification and delivered by email." }, { icon: "✦", title: "Mystic Plus", desc: "A $19 monthly subscription for premium 10-card readings, subject to fair-use controls." }].map((service) => <div className="service-card" key={service.title}><span className="icon">{service.icon}</span><h3>{service.title}</h3><p>{service.desc}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-tag">How it works</div><h2 className="section-title centered">A simple reflection practice</h2><div className="steps">{[{ num: "1", title: "Ask", desc: "Bring an open-ended question about a situation you want to reflect on." }, { num: "2", title: "Draw", desc: "Receive a three-card AI tarot interpretation." }, { num: "3", title: "Reflect", desc: "Consider which symbols and prompts feel useful for your next step." }, { num: "4", title: "Choose", desc: "Make your own decisions; the reading does not replace professional advice." }].map((step) => <div className="step" key={step.num}><div className="num">{step.num}</div><h4>{step.title}</h4><p>{step.desc}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-tag">From the Journal</div><h2 className="section-title centered">Guides and card meanings</h2><p className="section-sub centered">Educational tarot content to support a more thoughtful reading practice.</p><div className="services-grid">{latestPosts.map(post => <Link href={`/blog/${post.slug}`} className="service-card blog-teaser" key={post.slug}><span className="icon">📖</span><h3>{post.title}</h3><p>{post.excerpt}</p><span className="read-more" style={{ display: "inline-block", marginTop: 8, color: "var(--primary)", fontWeight: 600, fontSize: 14 }}>Read article →</span></Link>)}</div><div style={{ textAlign: "center", marginTop: 32 }}><Link href="/blog" className="btn-secondary">View all articles</Link></div></div></section>
    <section className="section cta-section"><h2 className="section-title centered" style={{ textAlign: "center" }}>Ready to reflect?</h2><p>Start with a free daily tarot reading.</p><Link href="/reading" className="btn-primary" style={{ display: "inline-flex" }}>✦ Get Your Free Reading</Link></section></>;
}
