export default function TermsPage() {
  return (
    <>
      <section className="page-header"><h1>Terms of Service</h1><p>Last updated: July 2026</p></section>
      <section className="section"><div className="container" style={{maxWidth:800,margin:"0 auto"}}>
        <div style={{marginBottom:24}}><h3 style={{fontSize:16,fontWeight:600,color:"var(--text-primary)",marginBottom:8}}>1. Service Description</h3>
        <p style={{color:"var(--text-secondary)",fontSize:14,lineHeight:1.7}}>MysticSage provides online tarot readings, astrology reports, numerology insights, and spiritual guidance for entertainment and wellness purposes only. All readings are generated by AI and are not a substitute for professional advice.</p></div>
        <div style={{marginBottom:24}}><h3 style={{fontSize:16,fontWeight:600,color:"var(--text-primary)",marginBottom:8}}>2. User Eligibility</h3>
        <p style={{color:"var(--text-secondary)",fontSize:14,lineHeight:1.7}}>You must be 18 years or older to use this service. By using MysticSage, you confirm that you are at least 18 years of age.</p></div>
        <div style={{marginBottom:24}}><h3 style={{fontSize:16,fontWeight:600,color:"var(--text-primary)",marginBottom:8}}>3. Payments & Refunds</h3>
        <p style={{color:"var(--text-secondary)",fontSize:14,lineHeight:1.7}}>All payments are processed securely through PayPal. Subscriptions auto-renew unless cancelled. Refund requests are handled on a case-by-case basis. Contact us at mountain0342@gmail.com for refund inquiries.</p></div>
        <div style={{marginBottom:24}}><h3 style={{fontSize:16,fontWeight:600,color:"var(--text-primary)",marginBottom:8}}>4. Limitation of Liability</h3>
        <p style={{color:"var(--text-secondary)",fontSize:14,lineHeight:1.7}}>MysticSage is provided for entertainment purposes. We make no guarantees about the accuracy of readings. We are not responsible for decisions made based on our content. Readings should not replace professional medical, legal, or financial advice.</p></div>
        <div style={{marginBottom:24}}><h3 style={{fontSize:16,fontWeight:600,color:"var(--text-primary)",marginBottom:8}}>5. Contact</h3>
        <p style={{color:"var(--text-secondary)",fontSize:14,lineHeight:1.7}}>For questions about these terms, contact us at mountain0342@gmail.com.</p></div>
      </div></section>
    </>
  );
}